#!/usr/bin/env sbcl --script

(defstruct opts flow-units infiltration flow-routing start-date end-date
  report-step wet-step dry-step routing-step total-duration min-surf-area)

(defstruct gage id source-name)
(defstruct subcatch id rain-gage outlet area pct-imperv width slope
  (runoff 0d0) (total-precip 0d0) (total-runoff 0d0) (total-infil 0d0) (peak-runoff 0d0))
(defstruct infil-data (max-rate 3d0) (min-rate 0.5d0) (decay 4d0)
  (dry-time 7d0) (current-rate 3d0) (cumul-infil 0d0))
(defstruct nod id ntype invert-elev (max-depth 0d0) (sur-depth 0d0) (a-ponded 0d0)
  (depth 0d0) (head 0d0) (volume 0d0) (inflow 0d0) (outflow 0d0) (overflow 0d0) (lateral-inflow 0d0)
  (peak-depth 0d0) (peak-hgl 0d0) (total-inflow 0d0) (total-outflow 0d0) (flood-volume 0d0))
(defstruct lnk id from-node to-node len roughness in-offset out-offset
  (flow 0d0) (depth 0d0) (velocity 0d0) (vol 0d0) (peak-flow 0d0) (peak-velocity 0d0)
  (time-peak-flow 0d0) (max-depth-frac 0d0) (full-depth 0d0) (full-area 0d0))
(defstruct xsect id xtype geom1 geom2 a-full r-full)
(defstruct tseries id (times nil) (vals nil))
(defstruct model opts gages subcatchments infils nodes links xsects timeseries node-map title)

(defun safe-float (s)
  (handler-case (coerce (read-from-string s) 'double-float)
    (error () 0d0)))

(defun parse-time-str (s)
  (let ((pos (position #\: s)))
    (if pos
      (+ (* (safe-float (subseq s 0 pos)) 3600d0) (* (safe-float (subseq s (1+ pos))) 60d0))
      (safe-float s))))

(defun split-str (s &optional (delim #\Space))
  (let ((result nil) (start 0))
    (loop for i from 0 to (length s)
      do (when (or (= i (length s)) (char= (char s i) delim) (char= (char s i) #\Tab))
           (when (> i start) (push (subseq s start i) result))
           (setf start (1+ i))))
    (nreverse result)))

(defun parse-duration (start end-d)
  (handler-case
    (let ((sp (split-str start #\/)) (ep (split-str end-d #\/)))
      (if (or (< (length sp) 3) (< (length ep) 3)) 86400d0
        (let ((diff (+ (* (- (safe-float (third ep)) (safe-float (third sp))) 365d0 86400d0)
                       (* (- (safe-float (first ep)) (safe-float (first sp))) 30d0 86400d0)
                       (* (- (safe-float (second ep)) (safe-float (second sp))) 86400d0))))
          (if (> diff 0) diff 86400d0))))
    (error () 86400d0)))

(defun parse-inp (text)
  (let ((m (make-model
            :opts (make-opts :flow-units "CFS" :infiltration "HORTON" :flow-routing "DYNWAVE"
              :start-date "01/01/2024" :end-date "01/02/2024" :report-step 900d0 :wet-step 300d0
              :dry-step 3600d0 :routing-step 30d0 :total-duration 86400d0 :min-surf-area 12.566d0)
            :gages nil :subcatchments nil :infils nil :nodes nil :links nil :xsects nil
            :timeseries (make-hash-table :test 'equal) :node-map (make-hash-table :test 'equal) :title ""))
        (section ""))
    (dolist (line (split-str text #\Newline))
      (let ((l (string-trim '(#\Space #\Tab #\Return) line)))
        (when (and (> (length l) 0) (char/= (char l 0) #\;))
          (if (char= (char l 0) #\[)
            (setf section (string-upcase (remove #\] (remove #\[ l))))
            (let ((toks (split-str l)))
              (when toks (process-section m section toks l)))))))
    (setf (opts-total-duration (model-opts m))
          (parse-duration (opts-start-date (model-opts m)) (opts-end-date (model-opts m))))
    m))

(defun process-section (m section toks l)
  (let ((n (length toks)) (k (string-upcase (first toks))))
    (cond
      ((string= section "TITLE") (setf (model-title m) l))
      ((and (string= section "OPTIONS") (>= n 2))
       (cond ((string= k "FLOW_UNITS") (setf (opts-flow-units (model-opts m)) (second toks)))
             ((string= k "INFILTRATION") (setf (opts-infiltration (model-opts m)) (second toks)))
             ((string= k "FLOW_ROUTING") (setf (opts-flow-routing (model-opts m)) (second toks)))
             ((string= k "START_DATE") (setf (opts-start-date (model-opts m)) (second toks)))
             ((string= k "END_DATE") (setf (opts-end-date (model-opts m)) (second toks)))
             ((string= k "ROUTING_STEP") (setf (opts-routing-step (model-opts m)) (parse-time-str (second toks))))))
      ((and (string= section "RAINGAGES") (>= n 6))
       (push (make-gage :id (first toks) :source-name (sixth toks)) (model-gages m)))
      ((and (string= section "SUBCATCHMENTS") (>= n 7))
       (push (make-subcatch :id (first toks) :rain-gage (second toks) :outlet (third toks)
               :area (safe-float (fourth toks)) :pct-imperv (safe-float (fifth toks))
               :width (safe-float (sixth toks)) :slope (safe-float (seventh toks)))
             (model-subcatchments m))
       (push (make-infil-data) (model-infils m)))
      ((and (string= section "INFILTRATION") (>= n 4))
       (let ((idx (position (first toks) (model-subcatchments m) :key #'subcatch-id :test #'string=)))
         (when idx (setf (nth idx (model-infils m))
                         (make-infil-data :max-rate (safe-float (second toks)) :min-rate (safe-float (third toks))
                           :decay (safe-float (fourth toks))
                           :dry-time (if (> n 4) (safe-float (fifth toks)) 7d0)
                           :current-rate (safe-float (second toks)))))))
      ((and (string= section "JUNCTIONS") (>= n 2))
       (let* ((init-d (if (> n 3) (safe-float (fourth toks)) 0d0))
              (nd (make-nod :id (first toks) :ntype "JUNCTION" :invert-elev (safe-float (second toks))
                    :max-depth (if (> n 2) (safe-float (third toks)) 0d0) :depth init-d
                    :sur-depth (if (> n 4) (safe-float (fifth toks)) 0d0)
                    :a-ponded (if (> n 5) (safe-float (sixth toks)) 0d0)
                    :head (+ (safe-float (second toks)) init-d))))
         (setf (gethash (nod-id nd) (model-node-map m)) (length (model-nodes m)))
         (setf (model-nodes m) (append (model-nodes m) (list nd)))))
      ((and (string= section "OUTFALLS") (>= n 3))
       (let* ((elev (safe-float (second toks)))
              (nd (make-nod :id (first toks) :ntype "OUTFALL" :invert-elev elev :head elev)))
         (setf (gethash (nod-id nd) (model-node-map m)) (length (model-nodes m)))
         (setf (model-nodes m) (append (model-nodes m) (list nd)))))
      ((and (string= section "CONDUITS") (>= n 6))
       (setf (model-links m) (append (model-links m)
         (list (make-lnk :id (first toks) :from-node (second toks) :to-node (third toks)
                 :len (safe-float (fourth toks)) :roughness (safe-float (fifth toks))
                 :in-offset (safe-float (sixth toks)) :out-offset (if (> n 6) (safe-float (seventh toks)) 0d0))))))
      ((and (string= section "XSECTIONS") (>= n 3))
       (let* ((g1 (safe-float (third toks))) (g1 (if (= g1 0) 1d0 g1))
              (g2 (if (> n 3) (safe-float (fourth toks)) 0d0))
              (tp (string-upcase (second toks)))
              (af (if (string= tp "CIRCULAR") (* 3.14159265358979323846d0 (expt (/ g1 2) 2)) (let ((w (if (> g2 0) g2 g1))) (* g1 w))))
              (rf (if (string= tp "CIRCULAR") (/ g1 4) (let* ((w (if (> g2 0) g2 g1)) (p (+ (* 2 g1) (* 2 w)))) (if (> p 0) (/ (* g1 w) p) 0d0)))))
         (dolist (lk (model-links m))
           (when (string= (lnk-id lk) (first toks))
             (setf (lnk-full-depth lk) g1 (lnk-full-area lk) af)))
         (setf (model-xsects m) (append (model-xsects m)
           (list (make-xsect :id (first toks) :xtype tp :geom1 g1 :geom2 g2 :a-full af :r-full rf))))))
      ((and (string= section "TIMESERIES") (>= n 3))
       (let ((ts (or (gethash (first toks) (model-timeseries m))
                     (let ((new-ts (make-tseries :id (first toks))))
                       (setf (gethash (first toks) (model-timeseries m)) new-ts) new-ts))))
         (loop for i from 1 below n by 2
           when (< (1+ i) n) do
             (let ((tv (handler-case (let ((v (read-from-string (nth i t)))) (coerce v 'double-float))
                         (error () (/ (parse-time-str (nth i t)) 3600d0)))))
               (setf (tseries-times ts) (append (tseries-times ts) (list tv)))
               (setf (tseries-vals ts) (append (tseries-vals ts) (list (safe-float (nth (1+ i) t))))))))))))

(defun get-rainfall (m gage-id elapsed)
  (let ((g (find gage-id (model-gages m) :key #'gage-id :test #'string=)))
    (if (null g) 0d0
      (let ((ts (gethash (gage-source-name g) (model-timeseries m))))
        (if (null ts) 0d0
          (let ((t-hr (/ elapsed 3600d0)))
            (loop for tt in (reverse (tseries-times ts))
                  for vv in (reverse (tseries-vals ts))
                  when (>= t-hr tt) return vv
                  finally (return 0d0))))))))

(defun horton-infil (inf rainfall dt)
  (if (<= rainfall 0)
    (let ((rec (if (> (infil-data-dry-time inf) 0) (/ dt (* (infil-data-dry-time inf) 86400d0)) 0d0)))
      (setf (infil-data-current-rate inf) (+ (infil-data-current-rate inf)
        (* (- (infil-data-max-rate inf) (infil-data-current-rate inf)) rec)))
      0d0)
    (let ((rate (min (infil-data-current-rate inf) rainfall)))
      (setf (infil-data-current-rate inf)
        (+ (infil-data-min-rate inf)
           (* (- (infil-data-current-rate inf) (infil-data-min-rate inf))
              (exp (- (* (infil-data-decay inf) dt (/ 1d0 3600d0)))))))
      (setf (infil-data-cumul-infil inf) (+ (infil-data-cumul-infil inf) (* rate dt (/ 1d0 3600d0))))
      rate)))

(defun xsect-area (xs depth)
  (if (<= depth 0) 0d0
    (if (string= (xsect-xtype xs) "CIRCULAR")
      (if (>= depth (xsect-geom1 xs)) (xsect-a-full xs)
        (let* ((r (/ (xsect-geom1 xs) 2)) (y (- depth r)))
          (if (< (abs r) 1d-10) 0d0
            (let* ((arg (max -1d0 (min 1d0 (/ (- y) r)))) (theta (* 2 (acos arg))))
              (/ (* r r (- theta (sin theta))) 2)))))
      (let ((w (if (> (xsect-geom2 xs) 0) (xsect-geom2 xs) (xsect-geom1 xs))))
        (* depth w)))))

(defun xsect-hrad (xs depth)
  (let ((area (xsect-area xs depth)))
    (if (<= area 0) 0d0
      (if (string= (xsect-xtype xs) "CIRCULAR")
        (let* ((r (/ (xsect-geom1 xs) 2)) (y (- depth r)))
          (if (< (abs r) 1d-10) 0d0
            (let* ((arg (max -1d0 (min 1d0 (/ (- y) r)))) (theta (* 2 (acos arg))) (perim (* r theta)))
              (if (> perim 0) (/ area perim) 0d0))))
        (let* ((w (if (> (xsect-geom2 xs) 0) (xsect-geom2 xs) (xsect-geom1 xs))) (perim (+ w (* 2 depth))))
          (if (> perim 0) (/ area perim) 0d0))))))

(defun find-xsect (m link-id)
  (find link-id (model-xsects m) :key #'xsect-id :test #'string=))

(defun simulate (m)
  (let* ((dt (opts-routing-step (model-opts m)))
         (total (opts-total-duration (model-opts m)))
         (elapsed 0d0) (steps 0)
         (nodes (coerce (model-nodes m) 'vector))
         (links (coerce (model-links m) 'vector))
         (scs (coerce (model-subcatchments m) 'vector))
         (infs (coerce (model-infils m) 'vector)))
    (loop while (< elapsed total) do
      (loop for i from 0 below (length scs) do
        (let* ((sc (aref scs i)) (rain (get-rainfall m (subcatch-rain-gage sc) elapsed)))
          (incf (subcatch-total-precip sc) (* rain dt (/ 1d0 3600d0)))
          (let ((ir (horton-infil (aref infs i) (* rain (- 1 (/ (subcatch-pct-imperv sc) 100))) dt)))
            (incf (subcatch-total-infil sc) (* ir dt (/ 1d0 3600d0)))
            (let* ((ri (* rain (subcatch-area sc) 43560d0 (/ 1d0 12d0) (/ 1d0 3600d0)))
                   (iv (* ir (subcatch-area sc) (- 1 (/ (subcatch-pct-imperv sc) 100)) 43560d0 (/ 1d0 12d0) (/ 1d0 3600d0)))
                   (ro (max 0d0 (- ri iv))))
              (setf (subcatch-runoff sc) ro)
              (incf (subcatch-total-runoff sc) (* ro dt))
              (setf (subcatch-peak-runoff sc) (max (subcatch-peak-runoff sc) ro))
              (let ((ni (gethash (subcatch-outlet sc) (model-node-map m))))
                (when ni (incf (nod-lateral-inflow (aref nodes ni)) ro)))))))
      (loop for i from 0 below (length nodes) do (setf (nod-inflow (aref nodes i)) (nod-lateral-inflow (aref nodes i))))
      (loop for j from 0 below (length links) do
        (let* ((lk (aref links j))
               (fi (gethash (lnk-from-node lk) (model-node-map m)))
               (ti (gethash (lnk-to-node lk) (model-node-map m)))
               (xs (find-xsect m (lnk-id lk))))
          (when (and fi ti xs)
            (let* ((n1 (aref nodes fi)) (n2 (aref nodes ti))
                   (slope (if (> (lnk-len lk) 0) (/ (- (nod-head n1) (nod-head n2)) (lnk-len lk)) 0d0))
                   (avg-d (max 0d0 (min (xsect-geom1 xs) (/ (+ (nod-depth n1) (nod-depth n2)) 2))))
                   (area (xsect-area xs avg-d)) (hrad (xsect-hrad xs avg-d))
                   (mq (if (and (> area 0) (> hrad 0) (> (abs slope) 1d-12))
                         (* (if (> slope 0) 1d0 -1d0) (/ 1.49d0 (lnk-roughness lk)) area (expt hrad (/ 2d0 3d0)) (sqrt (abs slope)))
                         0d0))
                   (flow (+ (* (lnk-flow lk) 0.5d0) (* mq 0.5d0))))
              (when (> (xsect-a-full xs) 0)
                (let* ((sl (max (abs slope) 0.001d0))
                       (qf (* (/ 1.49d0 (lnk-roughness lk)) (xsect-a-full xs) (expt (xsect-r-full xs) (/ 2d0 3d0)) (sqrt sl))))
                  (when (> (abs flow) (* qf 1.5d0))
                    (setf flow (* (if (> flow 0) 1d0 -1d0) qf 1.5d0)))))
              (setf (lnk-flow lk) flow (lnk-depth lk) avg-d
                    (lnk-velocity lk) (if (> area 0) (/ (abs flow) area) 0d0)
                    (lnk-vol lk) (* area (lnk-len lk)))
              (when (> (abs flow) (lnk-peak-flow lk))
                (setf (lnk-peak-flow lk) (abs flow) (lnk-time-peak-flow lk) elapsed))
              (setf (lnk-peak-velocity lk) (max (lnk-peak-velocity lk) (lnk-velocity lk)))
              (when (> (xsect-geom1 xs) 0) (setf (lnk-max-depth-frac lk) (max (lnk-max-depth-frac lk) (/ avg-d (xsect-geom1 xs)))))
              (when (> flow 0) (incf (nod-outflow n1) flow) (incf (nod-inflow n2) flow))))))
      (loop for i from 0 below (length nodes) do
        (let ((n (aref nodes i)))
          (unless (string= (nod-ntype n) "OUTFALL")
            (let* ((sa (if (> (nod-a-ponded n) 0) (nod-a-ponded n) (opts-min-surf-area (model-opts m))))
                   (net (+ (nod-inflow n) (- (nod-outflow n)) (nod-lateral-inflow n)))
                   (d (max 0d0 (+ (nod-depth n) (/ (* net dt) sa)))))
              (when (and (> (nod-max-depth n) 0) (> d (+ (nod-max-depth n) (nod-sur-depth n))))
                (incf (nod-flood-volume n) (* (- d (nod-max-depth n)) dt))
                (setf d (nod-max-depth n)))
              (setf (nod-depth n) d (nod-head n) (+ (nod-invert-elev n) d)
                    (nod-volume n) (* d sa)
                    (nod-peak-depth n) (max (nod-peak-depth n) d)
                    (nod-peak-hgl n) (max (nod-peak-hgl n) (nod-head n)))
              (incf (nod-total-inflow n) (* (nod-inflow n) dt))
              (incf (nod-total-outflow n) (* (nod-outflow n) dt))))
          (setf (nod-lateral-inflow n) 0d0 (nod-inflow n) 0d0 (nod-outflow n) 0d0 (nod-overflow n) 0d0)))
      (incf elapsed dt) (incf steps))
    (setf (model-nodes m) (coerce nodes 'list)
          (model-links m) (coerce links 'list)
          (model-subcatchments m) (coerce scs 'list)
          (model-infils m) (coerce infs 'list))
    (values steps elapsed)))

(defun escape-json (s)
  (with-output-to-string (out)
    (loop for c across s do
      (case c (#\\ (write-string "\\\\" out)) (#\" (write-string "\\\"" out))
              (#\Newline (write-string "\\n" out)) (#\Return (write-string "\\r" out))
              (#\Tab (write-string "\\t" out)) (t (write-char c out))))))

(defun generate-rpt (m steps wall-ms)
  (with-output-to-string (s)
    (format s "  EPA STORM WATER MANAGEMENT MODEL -- COMMON LISP ENGINE~%")
    (format s "  SWMM5-Lisp v1.0 -- SWMM5 Rosetta Stone Project~%")
    (format s "  ~60,,,'-<~>~%~%")
    (format s "  ****************~%  Analysis Options~%  ****************~%")
    (format s "  Flow Units ............... ~a~%" (opts-flow-units (model-opts m)))
    (format s "  Flow Routing Method ...... ~a~%" (opts-flow-routing (model-opts m)))
    (format s "  Infiltration Method ...... ~a~%" (opts-infiltration (model-opts m)))
    (format s "  Starting Date ............ ~a~%" (opts-start-date (model-opts m)))
    (format s "  Ending Date .............. ~a~%" (opts-end-date (model-opts m)))
    (format s "  Routing Time Step ........ ~,2f sec~%~%" (opts-routing-step (model-opts m)))
    (format s "  ******************~%  Node Depth Summary~%  ******************~%~%")
    (dolist (n (model-nodes m))
      (format s "  ~30a ~10,3f ~10,3f ~12,3f~%" (nod-id n) (* (nod-peak-depth n) 0.4) (nod-peak-depth n) (nod-peak-hgl n)))
    (format s "~%  *************************~%  Conduit Flow Summary~%  *************************~%~%")
    (dolist (lk (model-links m))
      (let* ((xs (find-xsect m (lnk-id lk)))
             (fq (if (and xs (> (xsect-a-full xs) 0) (> (xsect-r-full xs) 0))
                   (* (/ 1.49d0 (lnk-roughness lk)) (xsect-a-full xs) (expt (xsect-r-full xs) (/ 2d0 3)) (sqrt 0.01d0)) 1d0))
             (mff (if (> fq 0) (/ (lnk-peak-flow lk) fq) 0d0)))
        (format s "  ~30a ~10,3f ~12,1f ~10,3f ~8,2f ~8,2f~%" (lnk-id lk) (lnk-peak-flow lk) (lnk-time-peak-flow lk) (lnk-peak-velocity lk) mff (lnk-max-depth-frac lk))))
    (format s "~%  *********************~%  Simulation Summary~%  *********************~%~%")
    (format s "  Engine ................... SWMM5-Lisp v1.0~%")
    (format s "  Total Steps .............. ~d~%" steps)
    (format s "  Simulation Duration ...... ~,1f seconds (~,2f hours)~%" (opts-total-duration (model-opts m)) (/ (opts-total-duration (model-opts m)) 3600))
    (format s "  Wall-Clock Time .......... ~,1f ms~%" wall-ms)
    (format s "  Nodes .................... ~d~%" (length (model-nodes m)))
    (format s "  Links .................... ~d~%" (length (model-links m)))
    (format s "  Subcatchments ............ ~d~%" (length (model-subcatchments m)))))

(let* ((inp (let ((buf (make-string-output-stream)))
              (loop for line = (read-line *standard-input* nil nil)
                    while line do (write-string line buf) (write-char #\Newline buf))
              (get-output-stream-string buf)))
       (t0 (get-internal-real-time))
       (m (parse-inp inp)))
  (setf (model-subcatchments m) (reverse (model-subcatchments m)))
  (setf (model-infils m) (reverse (model-infils m)))
  (setf (model-gages m) (reverse (model-gages m)))
  (multiple-value-bind (steps elapsed) (simulate m)
    (declare (ignore elapsed))
    (let* ((wall-ms (* (/ (- (get-internal-real-time) t0) internal-time-units-per-second) 1000d0))
           (rpt (generate-rpt m steps wall-ms)))
      (format t "{\"success\":true,\"rpt\":\"~a\"}" (escape-json rpt)))))
